
EVENT_STATE_HANDLED = 0
EVENT_STATE_UNHANDLED = 1

--[[
SDL_NOEVENT = 0
SDL_ACTIVEEVENT = 1
SDL_KEYDOWN = 2
SDL_KEYUP = 3
SDL_MOUSEMOTION = 4
SDL_MOUSEBUTTONDOWN = 5
SDL_MOUSEBUTTONUP = 6
SDL_JOYAXISMOTION = 7
SDL_JOYBALLMOTION = 8
SDL_JOYHATMOTION = 9
SDL_JOYBUTTONDOWN = 10
SDL_JOYBUTTONUP = 11
SDL_QUIT = 12
SDL_SYSWMEVENT = 13
SDL_EVENT_RESERVEDA = 14
SDL_EVENT_RESERVEDB = 15
SDL_VIDEORESIZE = 16
SDL_VIDEOEXPOSE = 17
SDL_USEREVENT = 24

EVT_SCENE_CLICK = 0
EVT_ACTOR_CLICK = 1
]]--

EVT_ACTIVE = 1
EVT_KEYDOWN = 2
EVT_KEYUP = 3
EVT_MOUSEMOTION = 4
EVT_MOUSEBUTTONDOWN = 5
EVT_MOUSEBOTTONUP = 6
EVT_QUIT = 12
EVT_SCENE_CLICK = 100
EVT_ACTOR_CLICK = 101


