#!/bin/sh
# vim: set noexpandtab:

echo
echo '// vim: set noexpandtab:'
echo
echo '#ifndef CLASSES_H'
echo '#define CLASSES_H'
echo
echo 'namespace grail {'
echo '	'

grep -h '^\([ ]*\)class \(.*\)[^;]$' lib/*.h | awk '{ print $2 }' | sort | {
	while read NAME; do
		if [ "$NAME" != "Vector2d" -a "$NAME" != "Reference" ]; then
			echo "	class $NAME;"
		fi
	done
}

echo '	'
echo '} // namespace grail'
echo
echo '#endif // CLASSES_H'
echo

