
#ifndef VISUALIZE_H
#define VISUALIZE_H

#ifdef WITH_VISUALIZATION
	#define VISUALIZE_POLYGONS 1
	#define VISUALIZE_LINES 1
	#define VISUALIZE_SCENE 1
	#define VISUALIZE_GROUND 1

	#define VISUALIZE_COMPONENTS 1
	#define VISUALIZE_MAP 1

	#define VISUALIZE_HOTSPOTS 1
#endif

#endif // VISUALIZE_H

